
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asummwrujukuuhgtdbac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzdW1td3J1anVrdXVoZ3RkYmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzIwMDAsImV4cCI6MjA2MzUwODAwMH0.PvnMGNELZDsUoIqZBRNh4aIQxvuSCND7l6skgj2hoS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
